### ISSUE TITLE
When using wercker to merge master branch to staging

### ISSUE THREAD

**Issue by djtaylor333** [fd/wercker-step-git-merge#2]
When i added your deploy steps to my wercker.yml file, and try to deploy, I get this error:

```
export WERCKER_STEP_ROOT="/pipeline/git-merge-e69fe39e-c3d0-4839-bbb0-1f2391c1946a"
export WERCKER_STEP_ID="git-merge-e69fe39e-c3d0-4839-bbb0-1f2391c1946a"
export WERCKER_STEP_OWNER="simonmenke"
export WERCKER_STEP_NAME="git-merge"
export WERCKER_REPORT_NUMBERS_FILE="/report/git-merge-e69fe39e-c3d0-4839-bbb0-1f2391c1946a/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/git-merge-e69fe39e-c3d0-4839-bbb0-1f2391c1946a/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/git-merge-e69fe39e-c3d0-4839-bbb0-1f2391c1946a/artifacts"
export WERCKER_GIT_MERGE_SOURCE="master"
export WERCKER_GIT_MERGE_TARGET="staging"
source "/pipeline/git-merge-e69fe39e-c3d0-4839-bbb0-1f2391c1946a/run.sh" < /dev/null
Fetching origin
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
failed: could not fetch branches from the remote
```

This is my wercker.yml setup:

```
box: ruby
services:
#    - wercker/postgresql
build:
  steps:
    - bundle-install
    - script:
        name: rspec
        code: bundle exec rspec
deploy:
  steps:
    - simonmenke/git-merge@0.0.3:
        source: master
        target: staging
```

I also have a ssh-key pair setup between github and wercker.
The desire is to have, after a successful build on wercker for my master branch, to merge my master branch into my staging branch. From there Heroku will deploy my staging branch. 
Any help you can provide would be greatly appreciated.
